// <auto-generated />
using ASP.NET_Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NETCore.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20181214232404_Alumno_mig")]
    partial class Alumno_mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.NET_Core.Models.Alumno", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CursoId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new { Id = "00739574-fc7e-4efb-b327-8b798651fc98", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Felipa Diomedes Toledo" },
                        new { Id = "00aee35e-dc91-468d-8939-a938ce55e5dc", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Nicolás Nicomedes Toledo" },
                        new { Id = "0125201d-c7ed-447b-b5f5-fba207690e8a", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Felipa Diomedes Uribe" },
                        new { Id = "02e8a38c-7c27-4eb3-898f-fd241e9ab27c", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Eusebio Anabel Toledo" },
                        new { Id = "02ebae21-6cde-4468-a02a-392f0889ec6f", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Donald Rick Maduro" },
                        new { Id = "03f4430a-0eb6-4110-a97f-b17fdd14bcaf", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Felipa Freddy Uribe" },
                        new { Id = "04246fb2-6c53-4872-9dae-c3826f176932", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Donald Silvana Herrera" },
                        new { Id = "06d5887d-e457-464a-976d-750109245515", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Donald Silvana Sarmiento" },
                        new { Id = "07a16b3f-d342-482f-95de-d3b3e4749a34", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Farid Nicomedes Toledo" },
                        new { Id = "087ff771-ba6c-4398-a2dc-e51bb4d537f7", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Alvaro Nicomedes Herrera" },
                        new { Id = "0ac5b512-546c-4880-ba1b-63140786bc60", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Eusebio Rick Toledo" },
                        new { Id = "0061fd49-d5a7-4d05-937e-7d8b6bb0f470", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Alba Rick Ruiz" },
                        new { Id = "0160e946-adc3-403c-a460-b1b0587dc0c4", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Alba Anabel Sarmiento" },
                        new { Id = "01807352-078b-4ce8-8c7b-1ec3972b5154", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Felipa Murty Ruiz" },
                        new { Id = "02bf7184-ac5f-4b00-abc4-f17847cd8c96", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Alvaro Diomedes Sarmiento" },
                        new { Id = "02d94ab5-1a4d-44f2-acc0-3b0788494d65", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Donald Murty Herrera" },
                        new { Id = "03a43d82-7a6b-45f3-bd65-acd927c8492c", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Felipa Nicomedes Herrera" },
                        new { Id = "03f1e4d6-f668-40e0-9436-f88f7d5378d3", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Nicolás Nicomedes Toledo" },
                        new { Id = "04128daf-33a4-4f7e-9c2e-19cd3382e128", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Alvaro Anabel Toledo" },
                        new { Id = "042ac2c1-0c6c-4ae3-9ba6-5d1834e56adc", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Farid Anabel Herrera" },
                        new { Id = "045f7899-91bd-4ee8-8dd4-3626f0b6fc74", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Donald Silvana Ruiz" },
                        new { Id = "04720fd3-feac-4602-9c60-68b855f0a3ee", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Felipa Silvana Ruiz" },
                        new { Id = "049675f6-55bc-4a71-9e8d-90f951762aa5", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Felipa Silvana Sarmiento" },
                        new { Id = "04ad572b-216f-4706-b97f-36e2e697c50d", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Nicolás Silvana Trump" },
                        new { Id = "05a757bc-87b8-4652-8e1f-f98d7892a708", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Alvaro Silvana Maduro" },
                        new { Id = "066caee8-512e-4d7b-95d2-a0721e0724e3", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Alvaro Anabel Trump" },
                        new { Id = "06cb97a5-b7a8-4b6c-88dc-5f1a0738075e", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Donald Teodoro Toledo" },
                        new { Id = "076e28a4-50af-450c-8630-9bf3c28b852c", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Felipa Teodoro Trump" },
                        new { Id = "09b8cb48-e9dc-4f95-8d1c-6b8364073880", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Nicolás Murty Herrera" },
                        new { Id = "004a2909-77f6-4055-b1d5-76fc077c5418", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Farid Murty Herrera" },
                        new { Id = "0090af8f-c5c9-49ce-9322-b50c2aae98a3", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Eusebio Murty Trump" },
                        new { Id = "016aebdb-a817-4987-97ac-e3323ef6e901", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Alba Murty Maduro" },
                        new { Id = "01c99589-cd47-42c9-8a48-7379b1455195", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Alvaro Teodoro Toledo" },
                        new { Id = "020ea134-5c38-4871-b669-e904a554d8e2", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Felipa Rick Ruiz" },
                        new { Id = "0330cefb-9c08-4090-9697-908110e22f3d", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Donald Diomedes Ruiz" },
                        new { Id = "03a30d9e-86c8-4750-b5a9-553982c2d3cd", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Alvaro Nicomedes Ruiz" },
                        new { Id = "03a3d0ea-9c84-45fd-bd9d-1cc7ef24a50b", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Alvaro Nicomedes Trump" },
                        new { Id = "04eb25f4-83d2-4649-8406-00504f89223b", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Farid Diomedes Sarmiento" },
                        new { Id = "053b9232-5c98-4cf8-82d8-533c863169bf", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Nicolás Anabel Trump" },
                        new { Id = "059be249-ebfd-49f7-b768-1f0537e618d0", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Alba Silvana Ruiz" },
                        new { Id = "060951cd-2942-4a11-b881-acc789bed320", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Felipa Anabel Sarmiento" },
                        new { Id = "06a86bbd-1ed4-4bc2-b811-554feb8534ed", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Nicolás Rick Uribe" },
                        new { Id = "01a43381-d265-40ef-a538-e73d4940b5a2", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Alba Anabel Toledo" },
                        new { Id = "0297d59b-cda0-4f08-adc6-ee39abc2e2fc", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Alba Rick Sarmiento" },
                        new { Id = "02dc0ac7-13ca-46d8-9a2c-e8a03434f95c", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Donald Anabel Maduro" },
                        new { Id = "03ea873b-fa82-46b9-892e-2a5cc6164036", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Felipa Diomedes Toledo" },
                        new { Id = "045b10bf-0ea6-4559-9cbd-d8079cd48368", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Alvaro Teodoro Maduro" },
                        new { Id = "049e017c-6f9e-4704-ad37-d21b58c7d2ae", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Farid Murty Toledo" },
                        new { Id = "05fda2aa-9d0f-40ec-b855-f81e1b05e86a", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Alba Rick Ruiz" },
                        new { Id = "062ee0e6-ec94-4cfd-8581-8faf972dc041", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Alba Diomedes Sarmiento" },
                        new { Id = "0675ada0-cda2-481f-b5f5-be1cb3f91966", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Eusebio Murty Ruiz" },
                        new { Id = "07e92a3f-1d82-486b-82f9-6f6429fd22e5", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Eusebio Nicomedes Trump" },
                        new { Id = "08b8834f-0915-43a8-96d6-3ffcf5b8d443", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Farid Nicomedes Maduro" },
                        new { Id = "099fc324-6866-4b2c-8f40-e8d87f627313", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Alvaro Rick Uribe" },
                        new { Id = "09a2d7a6-523e-4483-98cb-54ddbfc4aedd", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Farid Murty Uribe" },
                        new { Id = "0a20af6a-dd4f-4148-8f44-09a22fdd54f1", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Nicolás Teodoro Sarmiento" },
                        new { Id = "0c177f1e-d98c-4cec-94ff-e65e73c73db0", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Alba Nicomedes Uribe" },
                        new { Id = "0ca0117b-5c97-4c86-8c10-e5b57bdd5b97", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Farid Rick Toledo" },
                        new { Id = "00f0b2cb-d6e8-4983-9ef5-827e9bdae248", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Felipa Diomedes Ruiz" },
                        new { Id = "019b3dd0-3042-4b6c-8774-f6e6e54d8ce3", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Eusebio Anabel Trump" },
                        new { Id = "035fa72e-24f3-4973-ac16-e1d015be37ce", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Alba Anabel Ruiz" },
                        new { Id = "036018d5-1d48-49cb-ba30-bb7fd968e638", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Nicolás Anabel Ruiz" },
                        new { Id = "038b5c0a-b82b-4ac5-8895-7dcea2b7b1c4", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Farid Murty Toledo" },
                        new { Id = "041eb4c0-d245-4400-b66f-5fd20594c1b4", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Alba Teodoro Ruiz" },
                        new { Id = "044b89ef-fd97-46f9-b2c7-c7ce12945e34", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Eusebio Rick Herrera" },
                        new { Id = "04525fff-89e0-4efc-9920-db81544cd0cf", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Alba Anabel Sarmiento" },
                        new { Id = "046804e2-f9f6-4fc7-bee9-aa6c51ef3d58", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Eusebio Silvana Trump" },
                        new { Id = "04955a7d-a8fe-4508-a310-601fad3e60fb", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Farid Murty Sarmiento" },
                        new { Id = "04ea40f1-8b8c-4cb5-8c22-0d86f0205dd8", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Donald Anabel Sarmiento" },
                        new { Id = "05e2a698-2f5b-475b-9372-2369788bcfc2", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Donald Teodoro Toledo" },
                        new { Id = "07c6040f-e947-4557-a4ba-0e1485c98612", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Nicolás Silvana Sarmiento" },
                        new { Id = "08d4dc0d-7e2a-4075-9033-67a90d1297ff", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Eusebio Diomedes Ruiz" },
                        new { Id = "0a92a596-d559-44b6-b379-36216b68c6d7", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Eusebio Teodoro Uribe" }
                    );
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Asignatura", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CursoId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new { Id = "92441002-fe0a-4532-b45f-f94b39fdef0f", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Matemáticas" },
                        new { Id = "f49ddfc6-9174-49e6-b54a-433c77e77fa1", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Educación Física" },
                        new { Id = "e89c0ba5-539f-475a-a88d-ca7a5ebfd917", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Castellano" },
                        new { Id = "df79d182-5640-4a53-8f12-5f75ee17a852", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Ciencias Naturales" },
                        new { Id = "b697a4a8-e8b8-4694-a073-0dfef05f120c", CursoId = "d7b61716-0f17-484b-b713-80a0e81773bd", Nombre = "Programación" },
                        new { Id = "8ae09880-1df3-4b09-9515-a51a74c70c5f", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Matemáticas" },
                        new { Id = "e003138c-8f23-40a2-b988-dc7090d342bd", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Educación Física" },
                        new { Id = "e9d27416-572e-4669-b06b-ad0642559b6b", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Castellano" },
                        new { Id = "05418926-cd47-4970-acdb-72568663a411", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Ciencias Naturales" },
                        new { Id = "260dc65b-4745-449f-8f28-17b71079b112", CursoId = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Nombre = "Programación" },
                        new { Id = "fbfbf512-793e-420d-8984-4e40cc1de477", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Matemáticas" },
                        new { Id = "6c819690-3f91-40e4-9f70-223007951029", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Educación Física" },
                        new { Id = "3bb9dc71-8bb1-4a25-a201-6261b95ea9b1", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Castellano" },
                        new { Id = "490038e7-2228-44ee-9f69-01049f36bc09", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Ciencias Naturales" },
                        new { Id = "41553e3f-30f1-40d4-a23e-5e538025a263", CursoId = "1945d8cd-b28a-418e-b316-ec13c99fb421", Nombre = "Programación" },
                        new { Id = "5583ca38-8766-497b-95b4-a6d83d0dc50a", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Matemáticas" },
                        new { Id = "58320dd3-341b-4289-ae0a-74f1a8bbb215", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Educación Física" },
                        new { Id = "0f82b37a-f754-4512-a6c9-07b7d1884bb9", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Castellano" },
                        new { Id = "bec79c3c-cbcc-4acb-b043-3b9d46d676a0", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Ciencias Naturales" },
                        new { Id = "ec2c0b01-b3d4-4ff8-a3bc-20932dbbdafa", CursoId = "e0299658-f08b-4096-8bb3-886a3f871817", Nombre = "Programación" },
                        new { Id = "a7feff0f-3d83-42d9-816c-19e85c9b4407", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Matemáticas" },
                        new { Id = "08388103-c881-40ca-acc5-ff693f7d797a", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Educación Física" },
                        new { Id = "29e1ac8e-ce34-4166-a5a2-87db1fd337d6", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Castellano" },
                        new { Id = "f626072a-d435-4e40-8820-bcfbba2dab67", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Ciencias Naturales" },
                        new { Id = "1a55ba09-e3af-47fa-b6f7-af1ecead431c", CursoId = "534a6463-72fa-49e5-92de-a44fd976edfe", Nombre = "Programación" }
                    );
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Curso", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dirección")
                        .IsRequired();

                    b.Property<string>("EscuelaId");

                    b.Property<int>("Jornada");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new { Id = "d7b61716-0f17-484b-b713-80a0e81773bd", Dirección = "Avenida Siempreviva", EscuelaId = "70f2abf1-af34-4a1f-9306-732c6e0a9775", Jornada = 0, Nombre = "101" },
                        new { Id = "3c61ce53-0d01-4a1b-ab49-4f74f4719df5", Dirección = "Avenida Siempreviva", EscuelaId = "70f2abf1-af34-4a1f-9306-732c6e0a9775", Jornada = 0, Nombre = "201" },
                        new { Id = "1945d8cd-b28a-418e-b316-ec13c99fb421", Dirección = "Avenida Siempreviva", EscuelaId = "70f2abf1-af34-4a1f-9306-732c6e0a9775", Jornada = 0, Nombre = "301" },
                        new { Id = "e0299658-f08b-4096-8bb3-886a3f871817", Dirección = "Avenida Siempreviva", EscuelaId = "70f2abf1-af34-4a1f-9306-732c6e0a9775", Jornada = 1, Nombre = "401" },
                        new { Id = "534a6463-72fa-49e5-92de-a44fd976edfe", Dirección = "Avenida Siempreviva", EscuelaId = "70f2abf1-af34-4a1f-9306-732c6e0a9775", Jornada = 1, Nombre = "501" }
                    );
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Escuela", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AñoDeCreación");

                    b.Property<string>("Ciudad");

                    b.Property<string>("Dirección");

                    b.Property<string>("Nombre");

                    b.Property<string>("Pais");

                    b.Property<int>("TipoEscuela");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new { Id = "70f2abf1-af34-4a1f-9306-732c6e0a9775", AñoDeCreación = 2005, Ciudad = "Bogotá", Dirección = "Avenida Siempreviva", Nombre = "Platzi School", Pais = "Colombia", TipoEscuela = 1 }
                    );
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Evaluación", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlumnoId");

                    b.Property<string>("AsignaturaId");

                    b.Property<string>("Nombre");

                    b.Property<float>("Nota");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Alumno", b =>
                {
                    b.HasOne("ASP.NET_Core.Models.Curso", "Curso")
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Asignatura", b =>
                {
                    b.HasOne("ASP.NET_Core.Models.Curso", "Curso")
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Curso", b =>
                {
                    b.HasOne("ASP.NET_Core.Models.Escuela", "Escuela")
                        .WithMany("Cursos")
                        .HasForeignKey("EscuelaId");
                });

            modelBuilder.Entity("ASP.NET_Core.Models.Evaluación", b =>
                {
                    b.HasOne("ASP.NET_Core.Models.Alumno", "Alumno")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AlumnoId");

                    b.HasOne("ASP.NET_Core.Models.Asignatura", "Asignatura")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AsignaturaId");
                });
#pragma warning restore 612, 618
        }
    }
}
